# permissions for end users to view childprocesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: childprocess-viewer-role
rules:
- apiGroups:
  - childprocess.cezhang
  resources:
  - childprocesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - childprocess.cezhang
  resources:
  - childprocesses/status
  verbs:
  - get
