
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - childprocess.cezhang
  resources:
  - childprocesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - childprocess.cezhang
  resources:
  - childprocesses/finalizers
  verbs:
  - update
- apiGroups:
  - childprocess.cezhang
  resources:
  - childprocesses/status
  verbs:
  - get
  - patch
  - update
